version: "3.8"

services:
  postgres:
    image: postgres:14
    env_file: ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  hardhat-node:
    build:
      context: ../contracts
    command: npx hardhat node
    ports:
      - "8545:8545"

  backend:
    build:
      context: ../backend
    ports:
      - "3001:3001"
    env_file: ../.env
    depends_on:
      - postgres
      - hardhat-node

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
